import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * esbuild plugin: resolve `import 'mermaid'` to `window.mermaid` at runtime.
 * Obsidian bundles Mermaid.js internally but doesn't expose it as a
 * CommonJS/ESM module. This plugin makes `@mermaid-js/layout-elk`
 * (which imports from `mermaid`) work by redirecting to the global.
 */
const mermaidGlobalPlugin = {
	name: "mermaid-global",
	setup(build) {
		build.onResolve({ filter: /^mermaid$/ }, () => ({
			path: "mermaid",
			namespace: "mermaid-global",
		}));
		build.onLoad({ filter: /.*/, namespace: "mermaid-global" }, () => ({
			contents: "module.exports = globalThis.mermaid;",
			loader: "js",
		}));
	},
};

const sharedExternal = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

// ── Main plugin bundle (excludes ELK to keep size small) ──
const mainContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [mermaidGlobalPlugin],
	external: [...sharedExternal, "@mermaid-js/layout-elk"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
});

// ── ELK layout engine bundle (loaded on demand) ──
const elkContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: [require.resolve("@mermaid-js/layout-elk/dist/mermaid-layout-elk.core.mjs")],
	bundle: true,
	plugins: [mermaidGlobalPlugin],
	external: builtins,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	minify: prod,
	outfile: "elk-layout.js",
});

if (prod) {
	await mainContext.rebuild();
	await elkContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
	await elkContext.watch();
}
